version: "3"
services:
  db:
    image: postgres:12-alpine
    container_name: Db
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=to_do_list
    ports:
      - "5432:5432"